### PR TITLE
RDF4J Implementation (based on Sesame impl)

### PR DESCRIPTION
**Pull request by wherget**
This PR adds an `rdf2go.impl.rdf4j` artifact, which allows the use of Eclipse RDF4J (formerly known as Sesame 4.1) with RDF2Go.

Basically, I took the Sesame implementation, adapted all the dependencies, and took care of the API changes I could find (most of which were `URI` to `IRI` conversions).

Further improvements:
- Uses RDF4Js Json-LD RIO implementation instead of a third party one, simplifying dependencies
- The RIO packages are only `test` scoped now
- Targets Java8 (since RDF4J uses the `Optional<T>` feature)

Unfortunately I needed to temporarily remove the `.gitattributes` file. Not sure what `git`'s idea is about that. To me it looks as though everything was committed with CRLF in the last "Normalize line endings" commit, when it should have been LF.

### CODE REVIEW

**Comment by l337r007** [comment]
Updated the PR with a version that avoids "Normalize line endings". Still, d58ab13 induces a whole-file recommit of the two relevant poms.

**Comment by stuehmer** [comment]
Thank you for your work! Give me a few days to take a look and I will merge the pull request.

**Comment by ansell** [comment]
Note that the first versions of Eclipse RDF4J are not technically released yet. The builds on Maven Central are all "Milestone" builds (M1/M2/etc.) that the Eclipse Foundation hasn't put through the full release procedure yet.

**Comment by stuehmer** [comment]
Thanks Peter. It will be some days until I fix #16 and get the old release pipeline back to work until I can put any of this on Maven Central myself. Hopefully, the Eclipse versions will be there then or I publish snapshots first.
As a last step I will later get rid of the `rdf2go.impl.sesame` artefact in favor of @wherget 's new `rdf2go.impl.rdf4j` which currently exists in parallel.

**Pull request merged**
